README.md
=> Add some color!

.travis.yml, README.md, bower.json, package.json, tests/dummy/app/services/store.js
=> Enable TravisCI.

config/release.js, package.json
Running `ember release` will do the following with this update:
1. Update package.json/bower.json version numbers to the next patch
version (or minor if `ember release --minor` is ran).
2. Commit those changes.
3. Tag the repo with `v` new version number.
4. Push commit and tag to repo.
5. Run `npm publish`.
=> Update ember-cli-release to make new releases easier.

README.md, addon/resolver.js, addon/routes.js, blueprints/in-repo-engine/routable-files/lib/__name__/addon/routes.js, tests/dummy/lib/ember-blog/addon/routes.js
=> Introduce buildRoutes function to wrap route map exports

addon/-private/engine-ext.js, addon/-private/engine-instance-ext.js
Addressing #76. I know @dgeb mentioned working on some updates to this addon, but this will hopefully unblock folks looking to use it in the meantime.
=> Update registrations to work with recent Ember changes

addon/-private/router-ext.js
Should have been part of https://github.com/dgeb/ember-engines/pull/110
=> part 2 of engine within engine fix

addon/-private/engine-ext.js, addon/-private/engine-instance-ext.js, addon/-private/keywords/mount.js
See https://github.com/emberjs/ember.js/pull/13503
=> [Clean] Boot + initializer concerns have been moved upstream.

addon/-private/engine-instance-ext.js, tests/unit/engine-instance-test.js
See https://github.com/emberjs/ember.js/pull/13526
=> [Clean] Engine dependency cloning moved upstream.

addon/-private/keywords/mount.js, tests/acceptance/routeless-engine-demo-test.js, tests/dummy/lib/ember-chat/addon/components/hello-world.js, tests/dummy/lib/ember-chat/addon/templates/components/hello-world.hbs, tests/dummy/lib/ember-chat/addon/views/application.js
Fixes #126.
Includes and supercedes PRs #135 and #138.
=> Refactor mount keyword implementation.

addon/-private/keywords/mount.js, tests/acceptance/routeless-engine-demo-test.js, tests/dummy/lib/ember-chat/addon/components/hello-world.js, tests/dummy/lib/ember-chat/addon/templates/components/hello-world.hbs, tests/dummy/lib/ember-chat/addon/views/application.js
Applies #142 to `v0.2` branch to fix usage of `mount` keyword in routeless engines.
=> v0.2 - Refactor mount keyword implementation.

guides/02-what-are-engines.md
Structure was spelled wrong (sturcture) on line 13.
=> Fix a typo

blueprints/in-repo-engine/index.js
Apply 763932280798f8436098384011b9a3753b533ab0 to `master` branch.
=> Simplify route blueprint lookup through the use of `lookupBlueprint`.

addon/-private/engine-ext.js
Moved upstream via https://github.com/emberjs/ember.js/pull/13842
=> [Clean] Remove `component-lookup:main` registration.

README.md, tests/dummy/config/environment.js
See https://github.com/emberjs/ember.js/pull/13855
=> Engines feature flag enabled by default in Ember.

lib/engine-addon.js, lib/engine-config-from-meta.js, tests/unit/engine-instance-test.js
=> Generate engine config in separate method

addon/-private/engine-instance-ext.js, tests/acceptance/routeable-engine-demo-test.js
=> Move getEngineParent check to _bootSync

blueprints/in-repo-engine/routeless-files/lib/__name__/config/environment.js
This seems to be intentional? My linter complains about it ;(
=> Add missing semicolon.

lib/rollup-funnel.js, package.json
[EE-231] Changing Rollup Funnel to use Path-Posix library for cross-OS compatibility
=> [EE-231] Symlink Failure - Directory Name resolution

blueprints/in-repo-engine/index.js
=> Fixes in-repo-engines on cli ^2.9.0

lib/engine-addon.js, package.json
https://github.com/broccolijs/broccoli-funnel/pull/80
=> Bump broccoli-funnel to fix rebuild issues.

lib/engine-addon.js
=> Add allowEmpty to Funnels with srcDirs

lib/engine-addon.js
Improves build and re-build performance.
cc @nathanhammond
=> Don't use rollup-funnel for non-lazy builds

README.md
=> Clarify path to routes.js and add demo project links

.npmignore, .travis.yml, lib/rollup-funnel.js, node-tests/rollup-funnel-test.js, package.json
Addressing #256 & #257 
cc @stefanpenner @nathanhammond @rwjblue
=> Add tests for RollupFunnel + make it stable

.gitignore, .travis.yml, appveyor.yml, node-tests/acceptance/build-test.js, node-tests/helpers/compare-build.js, package.json, testem-node.js
Initial pass at addressing: https://github.com/ember-engines/ember-engines/issues/287
It's worth noting that with this approach, if we intentionally change the build output, then we will have a failing test. I think this is fine as it will force us to acknowledge when we're changing the semantics of the build.
=> Add build acceptance test

addon/-private/link-to-component.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/eager-blog/addon/routes.js, tests/dummy/lib/eager-blog/addon/templates/application.hbs, tests/dummy/lib/eager-blog/addon/templates/post.hbs
This PR resolves the issue described in #285 and also includes a test that was previously failing. While the test does work, I do feel like there may be a better way to test this, possibly in an integration test?
Fixes #285
=> Fix current-when behaviour within an engine

blueprints/in-repo-engine/index.js, blueprints/in-repo-engine/routable-files/lib/__name__/addon/engine.js, blueprints/in-repo-engine/routable-files/lib/__name__/addon/resolver.js, blueprints/in-repo-engine/routable-files/lib/__name__/package.json, blueprints/in-repo-engine/routeless-files/lib/__name__/addon/engine.js, blueprints/in-repo-engine/routeless-files/lib/__name__/addon/resolver.js, blueprints/in-repo-engine/routeless-files/lib/__name__/package.json
Similar to what Ember-CLI apps have. Some other minor changes in here as well.
Primarily prepping for a solution to https://github.com/ember-engines/ember-engines/issues/267.
=> Add resolver.js file to blueprint

addon/-private/engine-ext.js, addon/components/link-to-component.js, addon/components/link-to-external-component.js, app/components/link-to-external.js
=> Export link-to components in ember-engines namespace

addon-test-support/engine-resolver-for.js, tests/dummy/lib/ember-blog/addon/components/hello-name.js, tests/integration/engine-resolver-test.js
As discussed in https://github.com/ember-engines/ember-engines/issues/267.
=> Add engine-resolver-for test helper

lib/engine-addon.js
Since the upstream RFC and feature have been merged, we can clean this code up a bit.
=> Use public cacheKeyForTree method and remove ADDON_TREE_CACHING experiment

addon/-private/router-ext.js
Upstream changes are removing the `_populateQPMeta` method on `Ember.Route` instances (in order to prevent the corresponding controller from being eagerly looked up).
This preserves the same semantics, but avoids usage of `route-meta` and invocation of `handler._populageQPMeta` if it is not present.
=> Avoid eagerly populating QP meta when possible.

package.json, tests/dummy/lib/eager-blog/package.json, tests/dummy/lib/ember-chat/index.js, tests/dummy/lib/ember-chat/package.json
Fixes some minor deprecation warnings that were being thrown when running the tests.
=> Fix deprecation warnings

blueprints/in-repo-engine/index.js
=> Fix in-repo-engine generation with EmberCLI 2.13.0-beta.1

addon/components/link-to-component.js, tests/dummy/lib/eager-blog/addon/templates/application.hbs
=> Account for multiple routes in link-to's current-when property

lib/engine-addon.js, package.json, yarn.lock
broccoli-conditional-debug was renamed to broccoli-debug.
=> Update to renamed broccoli-debug.

node-tests/fixtures/should-compact-reexports/correct/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/correct/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/correct/node_modules/loader.js/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli-babel/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli-babel/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli-babel/node_modules/loader.js/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli/node_modules/loader.js/package.json, node-tests/fixtures/should-compact-reexports/old-loader/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/old-loader/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/old-loader/node_modules/loader.js/package.json, node-tests/unit/utils/should-compact-reexports-test.js, package.json, yarn.lock
=> Refactor should-compact-reexports tests

addon/-private/route-ext.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/routes/post.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs
Returning value from _externalAliasMethod, so that transitionToExternal and replaceWithExternal return a thenable Transition object
=> Fixed transitionToExternal and replaceWithExternal to return thenable Transition objects

lib/engine-addon.js
Based on https://github.com/ember-engines/ember-engines/pull/252
@trentmwillis Is this what you meant by "return early"?
=> Make addons accept asset objects /w environment properties

lib/engine-addon.js
As per https://github.com/ember-engines/ember-engines/issues/435#issuecomment-323118100
=> Fix: Default to no caching if cacheKeyForTree is not available in host

addon/-private/router-ext.js
Fixes https://github.com/ember-engines/ember-engines/issues/474.
=> Ensure the engine instances promise properly rejects if boot fails.

README.md
=> Update README with longhand lazyLoading syntax

package.json, yarn.lock
Simple bump of asset loader to include bugfix to avoid full page refresh.
=> Bump asset loader

blueprints/in-repo-engine/routable-files/lib/__name__/config/environment.js, blueprints/in-repo-engine/routeless-files/lib/__name__/config/environment.js
with the standalone version https://github.com/ember-engines/ember-engines/blob/master/blueprints/in-repo-engine/routable-files/lib/__name__/config/environment.js
=> sync blueprint

.eslintignore, index.js, lib/engine-addon.js, lib/engine-config-node-module.js, node-tests/acceptance/build-test.js, node-tests/fixtures/expected-manifests.json, node-tests/unit/engine-addon-test.js, node-tests/unit/index-test.js
Hopefully the last of these PRs. Prior work can be seen in https://github.com/ember-engines/ember-engines/pull/418 and https://github.com/ember-engines/ember-engines/pull/444.
Todo:
=> Lazy Engines + FastBoot

README.md, package.json, tests/dummy/lib/ember-blog/addon/services/example-service.js, tests/dummy/lib/ember-chat/addon/services/example-service.js, yarn.lock
=> Update Project and fix Eslint

lib/engine-addon.js, lib/utils/maybe-merge-trees.js, node-tests/unit/utils/maybe-merge-trees-test.js
It's fix #508 and replace the PR #509
=> Fix funnel + merges

lib/engine-addon.js, lib/utils/find-host.js, lib/utils/find-hosts-host.js, lib/utils/find-root.js, lib/utils/maybe-merge-trees.js, lib/utils/memoize.js, lib/utils/process-babel.js, lib/utils/should-compact-reexports.js, tests/dummy/lib/common-components/index.js, tests/dummy/lib/eager-blog/index.js, tests/dummy/lib/ember-blog/index.js, tests/dummy/lib/ember-chat/index.js
some cosmetic changes/cleanup/reduction/refactoring as I familiarize myself with the codebase.
I have additional cleanup/reduction steps planned, but would prefer to break them up.
=> Some superficial cleanup as I read

package.json, tests/acceptance/lazy-routeable-engine-test.js, tests/acceptance/routeable-engine-demo-test.js, tests/acceptance/routeless-engine-demo-test.js, tests/acceptance/teardown-test.js, yarn.lock
* remove all nested andThens
* ensure serial tests
* its just a nice thing
---
* also use `self` over `window`
* also use sinon sandbox, so restores always happen
=> Use async/await over andThen

lib/utils/maybe-merge-trees.js, yarn.lock
=> Fix older cli

lib/utils/should-compact-reexports.js, node-tests/unit/utils/should-compact-reexports-test.js
Previous it did not work with beta/pre-release versions
=> make compact-rexport code work correctly.

.npmignore
yarn.lock is ~ 50% of the final unpacked size :scream:
=> Add more to npmignore file.

package.json, yarn.lock
Good improvement - https://github.com/ember-engines/broccoli-dependency-funnel/pull/32/files
=> Bump broccoli-dependency-funnel

LICENSE.md, blueprints/in-repo-engine/routable-files/lib/__name__/index.js, blueprints/in-repo-engine/routeless-files/lib/__name__/index.js
=> Update LICENSE & Blueprint 

tests/acceptance/routeable-engine-demo-test.js, tests/acceptance/routeless-engine-demo-test.js, tests/integration/component-with-link-to-external-test.js, tests/integration/engine-resolver-test.js, tests/test-helper.js
=> Migrate Ember Tests to new API

README.md
=> Fix "Mounting" typo in README.md

lib/engine-addon.js, lib/utils/should-compact-reexports.js, node-tests/unit/utils/should-compact-reexports-test.js, package.json
=> Req. compileModules:true to use compact-reexports

.travis.yml
matrix and jobs are aliases
replace fail_fast with fast_finish (see https://github.com/ember-cli/ember-cli/pull/8943)
=> travis ci config fix

CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, README.md
This PR update information from 2019 to 2020, simplifies README. Also, add changelog missing to `v0.8.5`
=> [DOC] Update & Simplify informations

packages/ember-engines/ember-cli-build.js
Replicate https://github.com/ember-engines/ember-engines/issues/749
=> Ensure ember-engines are parallelizable.

packages/ember-engines/addon/-private/engine-ext.js
Fixes: embroider-build/embroider#857
Fixes: embroider-build/embroider#745
=> Add addon namespace to require so module can be found in embroider

CONTRIBUTING.md, LICENSE.md, README.md, packages/ember-engines/LICENSE.md, packages/ember-engines/README.md
This PR update information from 2020 to 2021, also updates the contributing section to the yarn workspace. 
cc: @dgeb @rwjblue
=> [DOC] Update Contributing Section and date info

packages/ember-engines/package.json, yarn.lock
Includes dependencySatisfies caching fix: https://github.com/embroider-build/embroider/pull/913 
Fixes: https://github.com/ember-engines/ember-engines/issues/784
=> Bump @embroider/macros 0.43.5

LICENSE.md, README.md, packages/ember-engines/LICENSE.md, packages/ember-engines/README.md, packages/ember-engines/package.json
=> update: Add author and update project date

packages/ember-engines/node-tests/fixtures/expected-manifests.json, packages/ember-engines/package.json, yarn.lock
this depends on #818 and should unblock https://github.com/ef4/ember-auto-import/pull/512 cc @thoov
=> Bump ember-asset-loader from 0.6.1 to 1.0.0

package.json, packages/ember-engines/package.json, yarn.lock
this can't be handled by dependabot as config needs to be updated as well
=> bump release-it from 14.2.1 to 15.5.0 and update release plugins

.github/workflows/ci.yml, packages/ember-engines/config/ember-try.js
another piece of overdue maintenance
=> Add more LTS version to CI matrix

packages/ember-engines/README.md
=> Update README.md with note about ember.js version support

.github/workflows/ci.yml, packages/ember-blog/addon/controllers/index.js, packages/ember-blog/addon/controllers/new.js, packages/ember-blog/addon/controllers/post.js, packages/ember-blog/addon/routes/post.js, packages/ember-blog/addon/templates/index.hbs, packages/ember-blog/addon/templates/new.hbs, packages/ember-blog/addon/templates/post.hbs
This PR extracts the one commit from #903 that actually fixes the problem. It looks like we're on a bit of a cliff with this project where we need old versions of things that just don't work when you upgrade them 🙈 probably something to discuss
the floating dependencies fail will be fixed by #902 👍
=> fix action deprecation

packages/ember-engines/.eslintignore, packages/ember-engines/node-tests/acceptance/build-test.js, packages/ember-engines/node-tests/acceptance/dedupe-addons-test.js, packages/ember-engines/node-tests/fixtures/app-template/app/app.js, packages/ember-engines/node-tests/fixtures/app-template/app/index.html, packages/ember-engines/node-tests/fixtures/app-template/app/router.js, packages/ember-engines/node-tests/fixtures/app-template/app/styles/app.css, packages/ember-engines/node-tests/fixtures/app-template/app/templates/application.hbs, packages/ember-engines/node-tests/fixtures/app-template/config/ember-cli-update.json, packages/ember-engines/node-tests/fixtures/app-template/config/environment.js, packages/ember-engines/node-tests/fixtures/app-template/config/optional-features.json, packages/ember-engines/node-tests/fixtures/app-template/config/targets.js, packages/ember-engines/node-tests/fixtures/app-template/ember-cli-build.js, packages/ember-engines/node-tests/fixtures/app-template/package.json, packages/ember-engines/node-tests/fixtures/app-template/public/robots.txt, packages/ember-engines/node-tests/fixtures/app-template/testem.js, packages/ember-engines/node-tests/fixtures/app-template/tests/helpers/index.js, packages/ember-engines/node-tests/fixtures/app-template/tests/index.html, packages/ember-engines/node-tests/fixtures/app-template/tests/test-helper.js, packages/ember-engines/node-tests/helpers/build.js, packages/ember-engines/node-tests/helpers/in-repo-addon.js, packages/ember-engines/node-tests/helpers/in-repo-engine.js, packages/ember-engines/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
This should unblock #903 and is a better reflection of how people will be consuming the addon 👍 
Edit: oh and this almost halves the CI time for the node tests 🎉
=> Move from using ember-cli-addon-tests to using fixturify-project for tests
