README.md, bin/install-test-addons.sh, lib/engine-addon.js, package.json, tests/acceptance/routeless-engine-demo-test.js, tests/dummy/lib/common-components/addon/components/spanish-greeting.js, tests/dummy/lib/common-components/addon/templates/components/spanish-greeting.hbs, tests/dummy/lib/common-components/app/components/spanish-greeting.js, tests/dummy/lib/common-components/index.js, tests/dummy/lib/common-components/package.json, tests/dummy/lib/ember-blog/index.js, tests/dummy/lib/ember-chat/addon/templates/application.hbs, tests/dummy/lib/ember-chat/addon/templates/components/hello-world.hbs, tests/dummy/lib/ember-chat/package.json
The EngineAddon extension ensures that an engine is able to access
addon dependencies as if it is an application. This is accomplished
by merging each addon’s `app` tree into the engine’s module
namespace.
=> Introduce `EngineAddon` extension.

package.json
broccoli-funnel and broccoli-merge-trees need to be available to
engine projects.
=> EmberAddon dependencies are not devDependencies.

addon/-private/keywords/mount.js
Ensure that a controller is available before attempting to set its model. This fixes a scenario when a route-less engine is mounted alongside a routable engine, and then the routable engine is 
visited. We will need further testing to fully understand the problem that this fixes.
=> Make mount#rerender more robust.

addon/-private/engine-ext.js
When `Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT` is on, the following error occurs, preventing the app from loading:
<pre>
TypeError: Attempting to register an unknown factory: `view:select`
</pre>
This change to use Ember's dependency injection fixes the issue.
See issue #69.
=> Fix error when legacy view support is on.

addon/-private/route-ext.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/routes/application.js, tests/dummy/lib/ember-blog/addon/routes/post.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs
Currently, `modelFor` in an Engine does not allow you to get the model from the `application` route, this is a simple fix to allow that.
=> Allow getting the modelFor application route

addon/-private/engine-ext.js
`Ember.Select` was deprecated and then removed as of
emberjs/ember.js#13144. This removes ember-engine's reference to
`Ember.Select` and should also fix the issue reported here: https://github.com/dgeb/ember-engines/issues/76#issuecomment-208985230
=> Remove reference to Ember.Select

addon/-private/router-dsl-ext.js, tests/helpers/start-app.js
=> Fix Ember.merge deprecations

addon/-private/route-ext.js
Issue #89 
Also fixed an issue where modelFor('...') was not returning the correct value when a transition was fully completed.
I don't think this is the best way to do this, would like some good feedback on this PR.  There are also a ton of places where a prefix based on the mount point is used, so may be a good idea to standardize at a higher level.
=> Pass the correct params object passed to the invoked model hook

addon/-private/keywords/outlet.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/components/hello-name.js, tests/dummy/lib/ember-blog/addon/templates/application.hbs, tests/dummy/lib/ember-blog/addon/templates/components/hello-name.hbs
Addressing #85 to the best of my ability.
**Root Issue**: During re-render, the `env.owner` was not correct within an `outlet`. This was because `outlet.render` was not called, meaning that the check for ensuring the proper `owner` never occurred.
**Solution:** Move the check for `owner` into `outlet.childEnv`, which is called on initial and subsequent render.
I'm not 100% certain this is the best solution as I still don't fully understand the rendering flows and hooks, but it works. I've included a previously failing test as well.
cc @krisselden
=> Fix environment owner during re-render

README.md, addon/-private/engine-ext.js, blueprints/in-repo-engine/routable-files/lib/__name__/addon/engine.js, blueprints/in-repo-engine/routeless-files/lib/__name__/addon/engine.js, package.json, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/engine.js, tests/dummy/lib/ember-blog/addon/initializers/ember-blog-initializer.js, tests/dummy/lib/ember-blog/addon/instance-initializers/ember-blog-instance-initializer.js
This enables initializers and instance-initializers inside engines.
The only change necessary to get instance-initializers running is altering the canonical addon/engine.js to invoke ember-load-initializers (which is analogous to what happens in app/app.js).
Getting the initializers running required an extention to the Engine class. Applications run them when they're told to boot, but no equivalent step happens for child engines, so instead we run them the first time we build an engine instance.
=> Run initializers and instance-initializers inside engines

README.md, addon/-private/engine-ext.js, addon/-private/engine-instance-ext.js, addon/-private/link-to-component.js, addon/-private/link-to-external-component.js, addon/-private/route-ext.js, addon/-private/router-ext.js, addon/initializers/engines.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/app/app.js, tests/dummy/lib/ember-blog/addon/engine.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs
This is a proof-of-concept for the recent updates to emberjs/rfcs#122 which attempts to address #57.
I would definitely like to see this feature move along, so I will update this branch with any future iterations on the RFC. This is last main feature I would need before using Engines in production projects.
=> External links / linking between engines

.travis.yml, bin/install-test-addons.sh, package.json, tests/dummy/lib/common-components/package.json, tests/dummy/lib/ember-chat/package.json
Addressing #94.
Essentially, this tells NPM to install the addons from the local file system. We want to keep the `prepublish` script however, so that the addons still get symlinked to make changes appear more easily.
=> Fix npm install for local development

addon/-private/router-ext.js, tests/acceptance/teardown-test.js, tests/dummy/lib/ember-blog/addon/routes/application.js, tests/dummy/lib/ember-blog/addon/services/example-service.js
This change causes routeable engine instances and everything in their containers to be properly destroyed when an app is destroyed.
The routeless ones are also missing this feature, but I will file a separate issue for that, since I'm less clear on the right way to fix it.
=> Routeable engine instances should be destroyed

addon/-private/router-dsl-ext.js
With these changes we can do some enginception, or mounting an engine within an engine.
Not sure if this is the right place to put the fix, but when processing an engine's routes, calling mount again breaks because this.options.engineInfo points to the outer engine's engineInfo.
=> fix for mounting engines within an engine

addon/-private/engine-ext.js
Remove registrations moved into ember core via https://github.com/emberjs/ember.js/pull/13459
Cleanup of patches moved upstream into ember core will be done on the `clean` branch so that `master` can continue to accept patches and work in a backward compatible way as much as possible. Once all the patches are moved upstream, we'll merge `clean` to `master` and bump the minor version.
=> [Clean] Eliminate registrations moved upstream.

tests/dummy/config/environment.js
The v0.2 branch will be maintained for use with production builds
of Ember v2.6. Since feature flags are only allowed in canary
builds, we should remove it for this branch in order to avoid
ember-cli warnings.
=> Remove engines feature flag for v0.2 branch.

README.md, blueprints/in-repo-engine/index.js, blueprints/in-repo-engine/routable-files/lib/__name__/addon/engine.js, blueprints/in-repo-engine/routable-files/lib/__name__/config/environment.js, blueprints/in-repo-engine/routeless-files/lib/__name__/addon/engine.js, blueprints/in-repo-engine/routeless-files/lib/__name__/config/environment.js, lib/engine-addon.js, lib/engine-config-from-meta.js, package.json, tests/dummy/app/app.js, tests/dummy/lib/ember-blog/addon/engine.js, tests/dummy/lib/ember-blog/config/environment.js, tests/dummy/lib/ember-chat/addon/engine.js, tests/dummy/lib/ember-chat/config/environment.js
Engines can now store their own configuration settings in 
`config/environment.js`. 
Adjust examples to import this module and use it to define 
`modulePrefix`.
=> Support engine configuration settings.

.gitignore
running 
```sh
./bin/install-test-addons.sh
```
leaves the user in a dirty git state. Because this is in the prepublish hook, it can happen when doing things like `npm link`.
=> Ignore node_modules from test engines/addons

addon/-private/keywords/mount.js
Any state that’s configured by the `mount` keyword will now have its 
owner set as the engine instance. This is preferable to the former 
method of relying on the presence of an application controller, which 
may not exist in all engines.
=> `mount` keyword now sets owner of state directly.

lib/engine-addon.js, tests/dummy/lib/ember-blog/package.json
Instead of overloading the usage of `configPath`, engines need their
own unique setting to specify their configuration file path.
[Fixes #149]
=> Allow custom engine config locations via `engineConfigPath`.

README.md
- Document route-serializer usage in ember-engines and how it differs from behavior outside of engines.
- Document change in loading behavior for failed transitions when crossing an engine boundary.
=> Document routing concerns for lazy engines

addon/-private/engine-instance-ext.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/controllers/post.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs, tests/dummy/lib/ember-blog/addon/templates/post/comments.hbs
The problem is the cache, which is used to keep track of the query param values. This cache is not shared between the application and the engine, but the routing is entirely done in the application. This causes the hydrating of unspecified query parameters during transitioning to fail, because the query param value is actually stored in the engine cache, but the hydration is done from the application cache.
My first PR for this addon, so any feedback is welcome. If you think this is correct fix I can try to add an acceptance test as well.
=> [0.2] Fix: Query parameters are not rehydrated

tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/controllers/post.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs, tests/dummy/lib/ember-blog/addon/templates/post/comments.hbs
Same test, which was pushed in v0.2 branch. The actual fix is in the ember codebase.
=> Test: Query parameters are not rehydrated

addon/-private/keywords/outlet.js, tests/dummy/app/templates/components/app-component.hbs, tests/integration/components/app-component-test.js
With new versions of ember-test-helpers, integration tests for components invoked in block-form fail in apps using `ember-engines`. This PR has a failing test to debug against.
The failures start with @rwjblue's recent changes to use `outlet`s in integration tests ([ref](https://github.com/switchfly/ember-test-helpers/pull/158)). So I am almost positive the issue lies somewhere in [the `outlet` keyword modifications](https://github.com/dgeb/ember-engines/blob/v0.2/addon/-private/keywords/outlet.js).
cc @tjni
=> Add failing integration test for v0.2

guides/04-creating-an-engine.md
Since the latest beta version of Ember (currently 2.8) [officially supports Engines](http://emberjs.com/blog/2016/07/25/ember-2-7-and-2-8-beta-released.html#toc_engines), we can now suggest users to download the beta instead of canary.
=> Suggest use of beta version instead of canary

.travis.yml, addon/-private/engine-ext.js, addon/-private/keywords/mount.js, bower.json, config/ember-try.js
Attempting to get 2.7 compatibility. Would be nice to be able to upgrade before the flag is enabled in 2.8.
=> Ember 2.7 compatibility

lib/engine-addon.js, lib/engine-config-from-meta.js
An attempt at addressing #164. This provides a hook which can be overriden to return a version of the config module that works in non-browser environments.
I'm open to other options, but this is the best one I could come up with currently.
=> Generate engine config in separate method

README.md
Replaces a reference in the README to the deprecated `ember/load-initializers` with one to `ember-load-initializers`
=> Replace deprecated ember/load-initializers in example

addon/-private/router-ext.js, addon/initializers/engines.js, bin/install-test-addons.sh, index.js, package.json, test-support/helpers/ember-engines/preload-assets.js, tests/acceptance/lazy-routeable-engine-test.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/app/router.js, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/routable-engine-demo.hbs, tests/dummy/lib/eager-blog/addon/engine.js, tests/dummy/lib/eager-blog/addon/routes.js, tests/dummy/lib/eager-blog/addon/templates/application.hbs, tests/dummy/lib/eager-blog/ember-config/environment.js, tests/dummy/lib/eager-blog/index.js, tests/dummy/lib/eager-blog/package.json, tests/dummy/lib/ember-blog/index.js, tests/test-helper.js, tests/unit/engine-instance-test.js
This is the complement to the Lazy Load Build PR (#173). There are three main parts to this PR:
1. Generate an Asset Manifest from the build assets of lazy engines (accomplished via [ember-asset-loader](https://github.com/trentmwillis/ember-asset-loader)).
2. Load lazy Engine assets dynamically at runtime (this is the bulk of the PR)
3. Modify default query params behavior such that they are ignored for Engines (otherwise we'll blow up on lazy Engines).
Todo:
=> Lazy Load Runtime

addon/-private/link-to-component.js, addon/-private/link-to-external-component.js, addon/-private/link-to-utils.js, addon/-private/router-ext.js, package.json
`EmptyObject` in Ember is an attempt to make creating `Object.create(null)` objects faster by avoiding the creation of an object with a null prototype.
In our case, these objects are not being created in a hot path repeatedly so the performance concern is not valid. Using `Object.create(null)` directly reduces our coupling to changes in Ember and embraces "the platform" (:troll:).
Fixes #196.
=> Remove usage of EmptyObject.

README.md
Since not including this property has been deprecated.
We should also consider improving the blueprints to include this property out of the box.
=> Add `lazyLoading` property to README

blueprints/in-repo-engine/index.js
It fixes a bug introduced by latest ember-cli changes: 
https://github.com/ember-cli/ember-cli/commit/79a4b40a1e7c0c9cb356fc2bcf3f0348a0191eb3#diff-006bfafbcbf2e60bf76521f12ad0cde8L19
Closes #217
=> Fixes in-repo-engines on cli 2.9.0-beta.2

.travis.yml, addon/-private/link-to-component.js, addon/-private/link-to-external-component.js, addon/-private/link-to-utils.js, config/ember-try.js
Replacing #201, by not including the #200 re-work which is still up in the air.
=> [v0.3] Fix link-to for Glimmer2 and ember-try update

guides/05-mounting-engines.md
After [51e1abe](https://github.com/dgeb/ember-engines/commit/51e1abe9493c552043756e0b95a857f28144bb55) , these instructions became unnecessary and confusing.
=> Remove confusing instructions

addon/-private/router-ext.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/app/controllers/post.js, tests/dummy/app/router.js, tests/dummy/app/routes/routable-engine-demo/after-model.js, tests/dummy/app/routes/routable-engine-demo/index.js, tests/dummy/app/routes/routable-engine-demo/redirect.js, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/post.hbs, tests/dummy/app/templates/routable-engine-demo/index.hbs, tests/dummy/lib/ember-blog/addon/routes/index.js, tests/dummy/lib/ember-blog/addon/routes/post.js, tests/dummy/lib/ember-blog/addon/templates/index.hbs, tests/dummy/lib/ember-blog/addon/templates/post.hbs
Addresses #209.
This should cover a large swath of Engines + QP use cases. There is a [super tiny change that needs to happen upstream](https://github.com/emberjs/ember.js/pull/14487) in order for this to pass.
=> Fix query params and add tests

package.json, tests/test-helper.js
Relevant issue to see what this changes: https://github.com/trentmwillis/ember-asset-loader/issues/21.
Testing with our LinkedIn app shows that the app can boot successfully in a FastBoot like environment.
=> Bump ember-asset-loader for FastBoot/SSR support

package.json
Temporary fix until we find the problem in broccoli-funnel. This fixes errors
of the following nature:
```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: ENOENT: no such file or directory, lstat '/Users/iradchenko/sandbox/ember-admin-demo/tmp/funnel-output_path-TLi8yNpH.tmp'
at Error (native)
at Object.fs.lstatSync (fs.js:982:18)
at symlink (/Users/iradchenko/sandbox/ember-engines/node_modules/symlink-or-copy/index.js:60:26)
at symlinkOrCopySync (/Users/iradchenko/sandbox/ember-engines/node_modules/symlink-or-copy/index.js:55:5)
at /Users/iradchenko/sandbox/ember-engines/node_modules/broccoli-plugin/read_compat.js:58:9
at tryCatch (/Users/iradchenko/sandbox/ember-engines/node_modules/rsvp/dist/rsvp.js:538:12)
at invokeCallback …
```
=> fix: lock broccoli-funnel to prevent rebuild error

lib/engine-addon.js
This flag should have always been set, but implementation details meant that it wasn't required to be in the past. Recent updates to `broccoli-funnel` "fixed" the non-throwing error, but only on rebuilds, and it's not actively throwing a helpful error, just encountering one and bailing.
Updates to broccoli-funnel messaging coming momentarily.
/cc @stefanpenner @trentmwillis
=> Specify allowEmpty to enable child engines to be safely merged.

addon/-private/link-to-external-component.js, app/components/link-to-external.js, tests/integration/component-with-link-to-external-test.js
Porting forward the main part of #205.
=> Re-export link-to-external so that it is available in integration tests

tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/routes.js, tests/dummy/lib/ember-blog/addon/routes/post.js, tests/dummy/lib/ember-blog/addon/routes/post/diggs.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs, tests/dummy/lib/ember-blog/addon/templates/post/error.hbs
Verifying that https://github.com/emberjs/ember.js/pull/14545 does what it needs to in this addon. Should restart the CI processes once the upstream PR lands.
=> Add tests for loading/error states

lib/engine-addon.js, lib/rollup-funnel.js
Currently `ember-engines` does unnecessary work in an all-eager scenario to remove and re-add routes. This stops that madness.
Manually tested that this produces identical output for the [`lazy-engine-testing`](https://github.com/nathanhammond/lazy-engine-testing) repo.
=> Work smarter, not harder.

addon/-private/link-to-utils.js
See http://emberjs.com/blog/2016/10/17/ember-2-9-released.html for details.
=> Use correct link-to method for 2.9.0.

lib/engine-addon.js
Getting errors on Ember-CLI master from this merge. It seems to have to do with the change in how the addon tree gets processed, as both trees now have our `.eslintrc.yml` file in it.
=> Add overwrite to mergeTrees

lib/engine-addon.js, package.json, tests/dummy/lib/common-components/package.json, tests/dummy/lib/ember-blog/package.json
Instead of manually invoking `broccoli-babel-transpiler` we will allow either `compileAddon` or `originalTreeForAddon` (both provided by Ember-CLI) to do transpiling for us. This should work on existing versions of Ember-CLI and prevents us from breaking in upcoming versions.
=> Let ember-cli compile addon js

lib/engine-addon.js
This change allows non-CSS assets to be gathered during the building of the styles tree and then later added to the public tree. For example, [ember-cli-eyeglass](https://github.com/sass-eyeglass/ember-cli-eyeglass) needs this so it can add any non-CSS assets returned from Eyeglass to the public tree.
This also makes the process for building a lazy engine consistent with how Ember CLI builds regular addons, in that it builds the styles tree before the public tree.
=> Build styles tree before building public tree.

addon/-private/router-ext.js, tests/unit/components/link-to-external-test.js
Addressing https://github.com/ember-engines/ember-engines/issues/294.
I think this solution will be fine to roll with. If a unit/integration attempts to do a transition, it could still hit an issue with the asset-loader not being present, but I don't believe unit/integration tests should be hitting that code path.
Another alternative is to move the service injection into an initializer, but I am unsure if that is better than this approach. I feel like this approach is less "magical" because it does not involve an additional external file.
=> Lookup asset-loader instead of injecting it

addon/-private/link-to-component.js, tests/acceptance/routeable-engine-demo-test.js, tests/dummy/lib/ember-blog/addon/templates/post.hbs
While addressing https://github.com/ember-engines/ember-engines.com/issues/8 I found a bug in the current implementation.
=> Properly link-to engine's application route

lib/engine-addon.js
In order to more effectively cache builds and have an easier to understand build process, we want to align lazy and eager (non-lazy) build processes. Right now the two types of builds do a lot of similar steps, but don't share any underlying implementation, this PR will seek to share as much implementation as is reasonably possible.
=> Align lazy and eager builds

.travis.yml, package.json
Updates Travis to only run build tests when `lib/*` or `index.js` are changed.
=> Run build tests only if appropriate changes were made

lib/engine-addon.js, lib/utils/memoize.js
We have a lot of small functions that are potentially called more than once for an Engine. By caching the return values of these functions, we can improve build performance by not doing redundant work.
The memoization done here assumes that only one output value ever occurs for the function, which is an assumption currently made by the build system.
=> Memoize build functions

lib/engine-addon.js
The proposed public API for this is `cacheKeyForTree`, with this  change when the symbol is removed (i.e. the feature is stable) a new version of ember-engines will not need to be released (and users will not accidentally fall back to uncached builds).
Specific scenarios:
* In older versions of ember-cli where `ember-cli/lib/experiments` is not present, we will not add the caching method at all.
* In versions of ember-cli with `ember-cli/lib/experiments` AND `ADDON_TREE_CACHING` symbol in the experiements file: that symbol will be used to name the method.
* In versions of ember-cli with a `ember-cli/lib/experiments` file that does not contain the `ADDON_TREE_CACHING` symbol in the experiments file (i.e. it has been promoted to a full public API) the method will be named …
=> Default `ADDON_TREE_CACHING` to `cacheKeyForTree`.

lib/engine-addon.js
Before this change, every addon that did an `app.import` on the argument passed in to the `included` hook would end up hoisting the thing imported all the way to the top.
This change passes in the engine itself as the `app` so that it is properly handled (addons downstream from a lazy engine end up in the lazy engines `engine-vendor.{js,css}` and addons downstream from eager engines end up in the top level `vendor.{js,css}`).
=> Prevent hoisting of all `app.import`'s.

lib/engine-addon.js
Reverts ember-engines/ember-engines#314
---
> I did this _very_ intentionally to maximize compatibility of `ember-engines` with the existing addon community. I noted a ton of places where `app.import` behavior inside of a nested addon relied on the top-level hoisting and would result in really strange or broken behavior–as in, the assets would not be present at the right time or place. (This mattered more for JS resources than it did CSS resources.) I spent a lot of time refactoring the engines build to support both `.import` behaviors and tested against numerous addons.
> So, there is already branching in the codebase to support doing the "right" thing for `this.import`–as evidenced by this single line change (there are other ways to change this that involve removing the branching). …
=> Revert "Prevent hoisting of all `app.import`'s."

lib/engine-addon.js
Adds a warning to the console that looks like:
```
WARNING: `app.import` should be avoided and `this.import` should be used instead. Using `app.import` forces the asset in question to be hoisted in all scenarios (regardless of `lazyLoading` flag).
Import performed on `tree-invocation-order`'s `app` argument at:
Error
at EmberApp.customHost.import (/Users/rjackson/src/open-source/ember-engines/lib/engine-addon.js:320:26)
at Class.included (/Users/rjackson/src/open-source/engine-testing/lib/tree-invocation-order/index.js:20:15)
at Class.superWrapper [as included] (/Users/rjackson/src/open-source/engine-testing/node_modules/core-object/lib/assign-properties.js:34:20)
at Class.included (/Users/rjackson/src/open-source/ember-engines/lib/engine-addon.js:329:28)
at EmberApp.<anonymous> …
```
=> Warn when `app.import` is used.

lib/engine-addon.js, package.json
New / tweaked styles pipeline is:
1. Invoke `preprocessTree` on all of the engines dependencies, with the raw `addon/styles` tree.
2. Process the raw tree through all the preprocessors setup in the registry.
3. Concat `**/*.css` from the result of 2 into `engine.css`
4. Concat vendor styles (dependent addons' `addon-styles` trees) into `engine-vendor.css`
5. Process `app.import`'s related to styles.
6. Invoke `postprocessTree` on all of the engines dependencies, with the final combined output of 3, 4, and 5.
Fixes #322
=> Ensure `preprocessTree` / `postprocessTree` are invoked properly for lazy engine styles.

README.md
Fixes a typo. `skip` -> `test`
`skip` is not used in the example snippet but `test` is.
=> Fix typo in component integration test example

README.md
Added notes explaining 
engines .4 -> ember 2.10.x
engines .5 -> ember 2.12.x
=> Update README.md to add ember compatibility info

addon/-private/router-ext.js
Ember 2.12 deprecates `_lookupFactory()` and adds `factoryFor()`.
Because ember-engines 0.5.x targets Ember 2.12 and newer, this commit does not provide a fallback to `_lookupFactory()` for older versions of Ember.
This change mirrors its counterpart in https://github.com/emberjs/ember.js/commit/eeb9175747ebf1cedf5de9541ac6d552b4a51707 , so even though I don't have a complete understanding of Ember internals, I believe this change is correct.
=> Ember 2.12: Use factoryFor instead of deprecated _lookupFactory

README.md
I was confused a little by the talking just about Ember. Is there also a dependency on a version of emberJS?
=> Updated dependancies to show version of EmberCLI

lib/engine-addon.js
Previously, if a lazy engine includes `app/styles` or any of its child addons include `app/styles` those styles were all being hoisted to the top level project's CSS assets.
This change handles the `styles` tree by ensuring that when the consuming app asks for `styles` tree we do not return one **AND** ensures that we do include `app/styles` in our custom build pipeline.
https://github.com/ember-engines/engine-testing/pull/12 was used to test this...
=> Ensure app/styles in child addons of lazy engines functions properly.

lib/engine-addon.js, tests/acceptance/lazy-routeable-engine-test.js
Due to the issue reported in https://github.com/ember-cli/ember-cli/issues/6779 our CI was passing when tests were actually failing. This PR is addressing the underlying reason they were failing (as https://github.com/ember-cli/ember-cli/issues/6779 will be fixed upstream via changes in ember-cli itself).
* Remove unneeded shimming around for `modules/` paths (this was not needed in ember-cli@2.12 and actually results in no file matches in ember-cli@2.13+).
* Fix test assertions that were confirming number of asset files loaded. The changes in https://github.com/ember-engines/ember-engines/pull/336 lead to us having an actual CSS file asset also, and the tests reported `not ok` but CI still passed (so we merged the PR). This fixes the assertions, and updates to have the tests actually …
=> Fix the build.

lib/engine-addon.js
In https://github.com/ember-cli/ember-cli/pull/6797 (specifically https://github.com/ember-cli/ember-cli/commit/e9758ebb2b3820abb983ccb297d077e2721dc414) the implementation of `otherAssets` was updated to use `this._mergeTrees`. Unfortunately, we are overriding the method and did not also implement an `_mergeTrees` method. This caused `ember-engines` to break when used with canary versions of ember-cli.
This brings over the `_mergeTrees` function as well, so it is also present. Thus correcting the issue.
=> Add `_mergeTrees` function for compat with ember-cli#master.

blueprints/in-repo-engine/routable-files/lib/__name__/config/environment.js
Whenever I generate a new engine, I have to add this semicolon. ¯\_(ツ)_/¯
=> Added semicolon at end of ENV variable

lib/engine-addon.js
When we call `treeFor('addon-styles')` the tree is returned with the `addon/styles` contents in `/`, however calling `this.eachAddonInvoke('treeFor', ['styles'])` returns the contents of dependent addons' `app/styles` tree _inside_ `app/styles`.
This change ensures that our dependencies `app/styles` contents are at the same level as our own `addon/styles` (and therefore can be imported from).
=> Ensure dependency styles are in same relative path as engine styles.

package.json
Since the `0.5.x` series is meant to be compatible with Ember-CLI 2.12, we should move to the beta channel and unbreak the build.
=> Move to ember-cli#beta channel

blueprints/in-repo-engine/index.js, blueprints/in-repo-engine/routable-files/lib/__name__/index.js, blueprints/in-repo-engine/routeless-files/lib/__name__/index.js
This allows you to specify `--lazy` when generating an in-repo-engine. Ex:
```bash
ember generate in-repo-engine foo --lazy true
```
If the option is omitted, nothing will be set, which preserve the current default of not having a default for `lazyLoading`.
=> Add lazy option to in-repo-engine blueprint

config/ember-try.js
AFAIK Ember 1.13 isn't supported in any version of ember-engines.
=> Remove Ember Try scenario for Ember 1.13

lib/engine-addon.js
This change fixes an issue where the treePath is hardcoded to a path instead of being configurable by the user. 
Fixes #355
=> Make the default addon tree an option

lib/engine-addon.js, node-tests/acceptance/build-test.js, node-tests/acceptance/dedupe-addons-test.js, node-tests/helpers/build.js, node-tests/helpers/in-repo-addon.js, node-tests/helpers/in-repo-engine.js, node-tests/helpers/matchers.js, tests/dummy/lib/ember-blog/addon/styles/addon.css
Addressing the first part of https://github.com/ember-engines/ember-engines/issues/329.
Figuring out duplicated addons is a bit more tricky than I anticipated. Largely because `eachAddonInvoke` is essentially a depth-first walk of the addon tree, but we would want it to be breadth-first so that we know all the addons at the previous level.
Note: I added an explicit CSS file to the ember-blog engine, because the styles tree would be undefined now that we deduplicate the styles trees.
Todo:
=> Deduplicate addons that already appear in a host

lib/engine-addon.js, node-tests/acceptance/deprecate-styles-flag-test.js
ember-engines@0.4 had a number of flaws with its style processing. A few examples of this are:
* All engine dependencies that have `app/styles` trees were **always** hoisted to the top level host application.
* Preprocessors were being ran only for the engines own styles, but not including any of its dependencies `app/styles` (causing `@import` to work in very bizarre ways).
* `preprocessTree` / `postprocessTree` hooks were never called for styles
All of these issues have been addressed in ember-engines@0.5, and so far there are no known issues with the fixes added to 0.5 for this. Unfortunately, applications in the wild came to rely on the broken behaviors :cry:, and now have completely broke styles when upgrading to ember-engines@0.5. 
This PR adds a mechanism for applications to …
=> Add deprecated flag to force ember-engines@0.4 styles behaviors.

.travis.yml, lib/engine-addon.js
The flag previously emulated 0.4.0, this updates the flag to emulate 0.5.0-beta.6.
The primary difference here is that https://github.com/ember-engines/ember-engines/pull/324 is now included in these changes...
=> Change useDeprecatedIncorrectCSSProcessing to emulate 0.5.0-beta.6.

lib/engine-addon.js, package.json, yarn.lock
Adds [broccoli-conditional-debug](https://github.com/rwjblue/broccoli-conditional-debug) as a dependency and begins instrumenting the styles portions of the build.
Once this lands, we can run a build like:
```
BROCCOLI_DEBUG=ember-engines:* ember b
```
And the instrumented trees are copied into `./DEBUG/` subfolder so that you can easily inspect them:
```
ember-engines:eager-in-eager:engine-style:input
ember-engines:eager-in-eager:styles
ember-engines:eager-in-lazy-in-lazy:engine-style:input
ember-engines:eager-in-lazy-in-lazy:styles
ember-engines:eager-in-lazy:engine-style:input
ember-engines:eager-in-lazy:styles
ember-engines:eager:engine-style:input
ember-engines:eager:styles
ember-engines:lazy-in-eager:engine-style:input
ember-engines:lazy-in-eager:engine-style:output …
```
=> Add broccoli-conditional-debug and begin instrumenting.

lib/engine-addon.js, lib/utils/should-compact-reexports.js, node-tests/acceptance/build-test.js, node-tests/acceptance/dedupe-addons-test.js, node-tests/fixtures/should-compact-reexports/correct/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/correct/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/correct/node_modules/loader.js/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli-babel/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli-babel/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli-babel/node_modules/loader.js/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/old-ember-cli/node_modules/loader.js/package.json, node-tests/fixtures/should-compact-reexports/old-loader/node_modules/ember-cli-babel/package.json, node-tests/fixtures/should-compact-reexports/old-loader/node_modules/ember-cli/package.json, node-tests/fixtures/should-compact-reexports/old-loader/node_modules/loader.js/package.json, node-tests/helpers/matchers-test.js, node-tests/helpers/matchers.js, node-tests/unit/utils/should-compact-reexports-test.js, package.json, yarn.lock
Fixes https://github.com/ember-engines/ember-engines/issues/265. Leverages [babel-plugin-compact-reexports](https://github.com/ember-engines/babel-plugin-compact-reexports).
TODO:
FOLLOW UPS:
=> Support compact re-exports

lib/engine-addon.js
Updates the `lazyLoading` option to accept a hash as its value. This is in preparation for a future PR to enable further options to be added to the lazy loading functionality.
Backwards compatibility has been retained by converting boolean values into a hash, e.g.
```js
lazyLoading: true
// Would be converted to
lazyLoading: {
enabled: true
}
```
Not sure if this needs tests and if so, where they should actually be located as I had a quick look but couldn't find any existing tests for the flag.
cc/ @rwjblue
=> Update `lazyLoading` option to accept a hash

blueprints/in-repo-engine/index.js, blueprints/in-repo-engine/routable-files/lib/__name__/index.js, blueprints/in-repo-engine/routeless-files/lib/__name__/index.js
This PR updates the `in-repo-engine` blueprint to use the new `lazyLoading` option format.
This change will also ensure that the `lazyLoading` option is **always** set (defaulting to false), as currently, generated engines produce the following deprecation warning.
```
DEPRECATION: {ENGINE_NAME} engine must specify the `lazyLoading.enabled` property as to whether the engine should be lazily loaded.
```
=> Use new `lazyLoading` format in `in-repo-engine` blueprint

lib/engine-addon.js, node-tests/acceptance/build-test.js
Attempt to fix #416 .
The change keeps the old logic for all invocations, which are not `treeFor`. For `treeFor`, the code will consult `cacheKeyForTree` to determine whether the trees from the host addon and the engine dependency addon are the same.
There is an open question of whether finding the corresponding host addon simply based on the name is enough. The host might have multiple instances of the same addon and we will only check for duplication against the first encountered one. Previously, the name was all cared about, so it worked just fine.
=> Use cacheKeyForTree to improve the addon dedup

lib/engine-addon.js, node-tests/acceptance/build-test.js, node-tests/fixtures/separate-routes/data.js
Introduces a new `lazyLoading.includeRoutesInApplication` option which enables lazy engines to output their `routes.js` file to a stand-alone file rather than bundling it into the hosts `vendor.js` file.
This will enable engines to be discovered dynamically at runtime rather than requiring engines to be declared statically at build time.
Still needs some tests which I will do once others have reviewed.
**Usage:**
```js
// Prevent routes being bundled into hosts vendor.js
lazyLoading: {
enabled: true,
includeRoutesInApplication: false
}
```
**TODO:**
cc/ @rwjblue @trentmwillis
=> Introduce `lazyLoading.includeRoutesInApplication` option

addon-test-support/engine-resolver-for.js
* extra error throws is wasteful
* legit failures in the resolver module are now no longer hidden.
=> use require.has instead of try/catch

addon/components/link-to-component.js
Adds an assertion if `{{link-to}}` is used within a routeless engine due to it not being supported.
Not sure if we still want to scope `{{link-to}}`'s within a routeless engine, or if the assertion alone is enough.
Closes #272
=> Assert if link-to is used within a routeless engine

lib/engine-addon.js
Without this, you cannot build engines with who's names are built-in array methods such as "filter".
The return type of the function is an `Object` not an `Array`
=> [BUGFIX release]: ancestorHostAddons return value

lib/engine-addon.js
This is private for now, because I suspect that we should actually deprecate this "auto concat all the things" behavior completely (in favor of the preprocessor in use emitting the correct file).
=> Extract private `_concatStyles` hook to allow customized concat strategies.

README.md
These files are already created with the correct content by the blueprint.
=> Removed content no longer  needed because of ember-in-repo-engine

node-tests/acceptance/build-test.js, node-tests/fixtures/expected-manifests.json, package.json, tests/acceptance/lazy-routeable-engine-test.js, yarn.lock
Primary changes included from 0.2.7 to 0.3.0:
* Update to latest dependencies (including ember-cli-babel@6).
* Drop support for Node < 4.
* Exclude empty files from the `asset-manifest.json`.
None of these changes are breaking for ember-engines@0.5.x users (we already dropped support for older Node and updated to ember-cli-babel@6), so this does not need to be a breaking change release for ember-engines.
TODO:
=> Update to latest ember-asset-loader version.

addon/-private/router-ext.js, package.json, tests/acceptance/lazy-routeable-engine-test.js
This pull tries to fix #471.
There are some changes in the acceptance tests that I don't like but I didn't find any other way to implement them.
I had to remove the exception adapter (`Ember.Test.adapter.exception`) because the router creates a new promise without an error handler ([L47:router.js](https://github.com/tildeio/router.js/blob/816c11f99bb169300ec98dbdb613bc2c0cf6c175/lib/router/handler-info.js#L47)). When I force an error in a transition, the exception is caught by the `ember-test` adapter making the test fail.
¿Do you know prevent the test failing?
Also I changed the `package.json` to trigger the build in Travis with the changes that I've done in [ember-asset-loader](https://github.com/ember-engines/ember-asset-loader/pull/57). This change should be removed.
=> Retry engine on assets error

README.md
While there is a section describing how to do unit/integration testing in in-repo engines, there is no information about how to test standalone engines. Currently, this information is spread out across multiple issues etc. This PR adds a section with basic information on how to test engines.
=> Add docs about how to test standalone engines

package.json
No need
"ember-cli-qunit" already have "ember-cli-test-loader"
=> Remove ember-cli-test-loader

lib/engine-addon.js, node-tests/acceptance/build-test.js
cc @trentmwillis 
The latest version of ember-engines is breaking an expectation in our apps that the "environment" key will always be set in `{{modulePrefix}}/config/environment`.
This change always grabs the `env` from the host application instead of assuming that it will be passed in from hooks like `contentFor`. @trentmwillis memoized the `engineConfig` method in the fastboot updates, and passing arguments to a memoized method can be problematic.
=> fix: ensure the "environment" is passed to the engine's config generator

addon/-private/engine-ext.js, addon/-private/engine-instance-ext.js, addon/-private/ext-require.js, addon/-private/router-ext.js, addon/engine-instance.js, addon/engine.js, tests/unit/engine-instance-test.js
Prior to these changes we were using `Ember.__loader.require` to access private internal modules from Ember itself. This was done because at the time, `Ember.Engine` / `Ember.EngineInstance` / etc were not exported globally from Ember itself (during the engines initial feature flag period long ago).
This changes ember-engines to remove all non-testing usages of `Ember.__loader.require`, and therefore makes it much more resilient to changes in Embers own internal module structure.
=> Fix issues with module paths changing in Ember 3.2.

lib/utils/maybe-merge-trees.js, node-tests/unit/utils/maybe-merge-trees-test.js
This correctly ignores empty trees..
=> Fix reduction of merge-trees

lib/utils/should-compact-reexports.js, node-tests/unit/utils/should-compact-reexports-test.js
We don't support ember-cli versions this old anymore, and it breaks beta builds.
=> remove ember-cli version test

lib/engine-addon.js
Passing a string as plugin options so that broccoli-babel-transpiler can serialize it for babel transpiler to work in parallel.
=> Fixing parallel babel

package.json, yarn.lock
Which now correctly supports `import * from ‘foo’;`
=> Bump babel-plugin-compact-reexports

addon/-private/router-ext.js
Resolves deprecation id: ember-console.deprecate-logger
=> Remove Usage of `Ember.Logger`

addon/-private/router-ext.js
Fixes #599.
```js
// This method used to be called `getHandler` and it is going to be called `getRoute`.
```
The comment says it all. If only I was able to read comments. 🙏 😂
=> fix(router-ext): hook into `getRoute`, if exsits

addon/-private/route-ext.js
Fixes #558.
As `Route#router` has been renamed `Route#_router` in Ember 3.6, `*ToExternal` is now broken. This PR fixes it by trying both keys.
https://github.com/emberjs/ember.js/commit/50a5a5df8172acbe6d287b1ba74b44485802eced#diff-7e252e0880a2b1de772cbcabaf3ddfb4L121
=> fix(route-ext): try `Route#_router` and `Route#router`

lib/engine-addon.js
https://github.com/ember-cli/ember-cli/pull/8264 has removed `_requireBuildPackages` in [`v3.7.0`](https://github.com/ember-cli/ember-cli/releases/tag/v3.7.0), which has been a no-op since [`v3.0.0-beta.1`](https://github.com/ember-cli/ember-cli/releases/tag/v3.0.0-beta.1). This breaks ember-engines.
=> fix(engine-addon): only call `_requireBuildPackages`, if it exists

tests/acceptance/lazy-routeable-engine-test.js
Makes a lazy-loading acceptance test more forgiving of the number of bundle load errors that are encountered on different versions of ember. Three are encountered in 3.7, while only two are encountered in 3.3. This difference does not seem to impact the behavior of the addon, yet does prevent CI from passing.
=> Make lazy routable acceptance test more forgiving

lib/utils/ensure-lazy-loading-hash.js, lib/utils/find-host.js, lib/utils/find-hosts-host.js, node-tests/unit/utils/ensure-lazy-loading-hash-test.js
It's ensure that lazyLoading is a hash on `find-host` and `find-host-host` utils
=> Fix find-host utils with lazyLoading hash

addon/engine-instance.js
We have a test that validates all module exports in our codebase. While updating ember-engines from 0.5.16, the test threw an error `Could not find module @ember/engines/instance imported from ember-engines/engine-instance`.
If I am right, it should have been `@ember/engine/instance` instead of `@ember/engines/instance`.
I checked in ember.js repo as well and this seems to be a typo.
Since things are still working inspite of this typo, I believe this file is unnecessary.
=> Remove unnecessary file

package.json
It's possible there's some reason we need to depend on ember-try directly, but it seems unlikely?
=> fix(deps): move ember-try to devDependencies

appveyor.yml, package.json
This was _effectively_ dropped in #619 (babel@7 requires Node 6+), but I wanted to make it more explicit.
=> Drop Node 4 support.

lib/engine-addon.js, node-tests/unit/engine-addon-test.js
The recent addition of the keyword check throws an error (`Cannot read property 'indexOf' of undefined`) if keywords are not present. This fix ensures that the warning is issued either way (with or without a keywords array) and also adds tests that would have previously failed.
=> Avoid errors when keywords array is not present.

README.md, lib/engine-addon.js, lib/utils/deeply-non-duplicated-addon.js, lib/utils/recover-addons.js, lib/utils/restore-original-addons.js, node-tests/acceptance/dedupe-addons-test.js, node-tests/unit/utils/deeply-non-duplicated-addon-test.js
Try to fix remaining "Shared addon deeper than engine" problem of https://github.com/ember-engines/ember-engines/pull/356.
An example of this problem copied from https://github.com/ember-engines/ember-engines/pull/356#issuecomment-288571816
> - project has dep on addon-derp
> - project has lazy engine engine-a
> - engine-a has engine addon-z
> - addon-z has addon-derp (addon-derp should not be duplicated)
For the example above, the `addon-derp` should not be duplicated, but without this PR it would be duplicated in the `vendor.js` of `engine-a`.
@rwjblue @trentmwillis @stefanpenner
=> Deduplicate addons in lazy engines that are nested dependencies of the engine

package.json
Fixed the true scenario - https://github.com/ember-engines/ember-engines/pull/384#issuecomment-321823354
@rwjblue @dgeb
=> Ensure `postprocessTree` to ran before `broccoli-asset-rev`

addon/components/link-to-component.js, addon/components/link-to-external-component.js, package.json, tests/integration/component-with-link-to-external-test.js, tests/unit/components/link-to-external-test.js, yarn.lock
[RFC #0459](https://emberjs.github.io/rfcs/0459-angle-bracket-built-in-components.html) changed the attribute name from `targetRouteName` to `route`.
Here's the PR: https://github.com/emberjs/ember.js/pull/17772
This is currently breaking the Ember v3.10.0-beta series.
=> fix(link-to): support angle-bracket invocation

package.json
This reverts commit e314a63dd51b6a21487490d0288afb90d5f729a0.
Reverting due to reports of production breakage in #632.  Specifically, the report was that this change resulted in _no_ fingerprinting being done for the asset manifest.
We need to investigate and figure out the right way to bring this back, I'll reopen the associated issue/PR so we can discuss it further.
=> Revert "ensure  to be ran before"

package.json
These platforms are both EOL'ed by the Node Foundation.
=> Drop support for Node 6 and 11.

lib/engine-addon.js, lib/utils/memoize.js, node-tests/unit/engine-addon-test.js, package.json, yarn.lock
Say we have a third-party asset we use only in a lazy-loaded in-repo engine, and we want to include it in the engine's bundle instead of the host app's. We try the normal ember app thing:
```js
// lib/my-lazy-engine/index.js
included(...args) {
this._super(...args);
this.import('node_modules/path/path/thingy.js', {
using: [{ transformation: 'amd', as: 'thingy' }]
});
}
```
This breaks three different ways:
1. Because it's in `node_modules`, [`EmberApp.import` tries to use `this._nodeModules`](https://github.com/ember-cli/ember-cli/blob/v3.1.4/lib/broccoli/ember-app.js#L1664-L1669), which doesn't exist.
1. Because it uses a `transformation`, [`EmberApp._import` tries to use `this._customTransformsMap`](https://github.com/ember-cli/ember-cli/blob/v3.1.4/lib/broccoli/ember-app.js#L1714), …
=> Allow importing from node_modules in lazy in-repo engines

lib/engine-addon.js, node-tests/acceptance/build-test.js
Related issue https://github.com/ember-engines/ember-engines/issues/386
Repro: checkout https://github.com/2hu12/ember-engine-verification/tree/included-in-lazy-engine-addon and `yarn && ember build`, it will get an error like
> Error: ENOENT: no such file or directory, open '/tmp/broccoli-816153N6Pco04ZikZ/out-189-broccoli_debug_debug_12_engine_vendor_js/vendor/external_dependency_name.js'
=> Fix "treeForVendor" for nested addon of lazyload engine

package.json, yarn.lock
Also, changes the package from `ember-maybe-import-regenerator` to `ember-maybe-import-regenerator-for-testing`, as this is only required for testing.
=> fix(deps): Fixes shipping regenerator-runtime to production by moving it to devDeps

package.json, yarn.lock
fix an error with .git when perform npm-install
See issue or PR on ember-asset-loader for more info:
https://github.com/ember-engines/ember-asset-loader/issues/83
https://github.com/ember-engines/ember-asset-loader/pull/84
=> use ember-asset-loader v0.6.1

packages/ember-engines/tests/acceptance/teardown-test.js
This test was disabled due to a failure on Ember 3.20.0, which has subsequently been fixed in Ember 3.20.5 (by https://github.com/emberjs/ember.js/pull/19106).
Closes #724
=> Re-enable routeless engine container cleanup test.

packages/ember-engines/lib/utils/ensure-lazy-loading-hash.js, packages/ember-engines/node-tests/unit/utils/ensure-lazy-loading-hash-test.js
Normally engine's parent is the project and the findHost loop stops at
the first level dependency engine. If an engine's parent is another
engine it's also fine. However if the parent is an addon that did not
specify lazyLoading the build breaks saying cannot read enabled of
undefined.  This change allows addon uses engines for its dummy app.
=> fix: findHost and findHostHost should allow undefined lazyLoading config

packages/ember-blog/addon/controllers/post.js, packages/ember-blog/addon/templates/post.hbs, packages/ember-engines/addon/components/link-to-component.js, packages/ember-engines/tests/acceptance/routeable-engine-demo-test.js
Fixes https://github.com/ember-engines/ember-engines/pull/668
Closes https://github.com/ember-engines/ember-engines/pull/693
https://github.com/ember-engines/ember-engines/pull/693 attempts to fix this same problem by avoiding a call to `set`, but I think that solution is not ideal as it is still adding side effects to `didReceiveAttrs`.
There is further potential for improvement here, but I only fixed the immediate issue I had so as to touch as small a surface as possible. Other possible areas where this fix may need to be replicated:
- `targetRouteName`
- `current-when`
Both of the above properties are ALSO `set` the same way `route` was, so it stands to reason that they may also have this same bug. We could try to fix them all here if you think it wise.
Similarly, `link-to-external` …
=> Add mount prefix to route via computed instead of set

.github/workflows/ci.yml, packages/ember-engines/addon/-private/engine-instance-ext.js, packages/ember-engines/addon/components/link-to-component.js, packages/ember-engines/addon/components/link-to-external.js, packages/ember-engines/config/ember-try.js, packages/ember-engines/package.json, packages/ember-engines/tests/integration/component-with-link-to-external-test.js, packages/ember-engines/tests/unit/components/link-to-external-test.js, yarn.lock
- Ensure _externalRoutes is defined on EngineInstance instances.
- Fix issues with LinkTo and LinkToExternal on Ember 3.24.0.
- Enable 3.24 on CI.
Related:
* https://github.com/emberjs/ember.js/pull/19223
* https://github.com/emberjs/ember.js/pull/19337
Closes #740
=> Fix compatibility with Ember 3.24+

packages/ember-engines/addon/-private/engine-ext.js, packages/ember-engines/addon/components/link-to-component.js, packages/ember-engines/addon/components/link-to-external.js, packages/ember-engines/package.json, yarn.lock
At the moment, using `@embroider/macros` prevents applications from leveraging parallelized builds. Since we were only using `dependencySatisfies` we can replace that with `gte` from `ember-compatibility-helpers` which _is_ parallelizable to avoid the issue.
Note: this is not a great long term solution (we really should be converging on usage of `@embroider/macros`), but unblocks things for now.
Fixes #749
Related to https://github.com/embroider-build/embroider/issues/671
=> Revert usage of `@embroider/macros`

packages/ember-engines/lib/engine-addon.js, packages/ember-engines/node-tests/unit/engine-addon-test.js
[More info explaining the why.](https://github.com/ember-engines/engine-blueprint/pull/27#discussion_r593773644)
Best to view the diff without whitespace changes, but basically what I've done is this:
```js
function buildEngine() {}
module.exports = {
buildEngine,
extend: buildEngine,
};
```
=> Expose a `buildEngine` function (avoid the appearance of being an `Ember.Object`)

packages/ember-engines/addon/-private/engine-instance-ext.js, packages/ember-engines/tests/dummy/app/app.js, packages/ember-engines/tests/test-helper.js, packages/ember-engines/tests/unit/engine-instance-test.js
Closes #625.
I'm guessing some of the deprecation details can be improved (id, message, ...).
=> Support non-camelized engine names (deprecate camelization)

packages/ember-engines/package.json, yarn.lock
this includes a bug fix in `broccoli-concat` where we weren't properly invalidating a cached value in some cases; for more information, see the following PR: https://github.com/broccolijs/broccoli-concat/pull/156
=> Update `broccoli-concat` to address a major issue with cache invalidation

packages/ember-engines/addon/components/link-to-external.js
This PR extends off the work done in ember.js repo here: https://github.com/emberjs/ember.js/pull/19477/files
since LinkToExternal extends LinkTo, we only want to run the assertion around using LinkTo inside of a routeless engine in the LinkTo class, and not the extension of LinkToExternal.
=> [BUGFIX LTS] override assertLinkToOrigin method to noop in ember-engines

packages/ember-engines/lib/engine-addon.js
This adds support for bundle addon caching as part of `ember-cli`; specifically, we need to access the real/target instance in the event we're seeing a proxy as part of `ancestorHostAddons`. If we don't do this, the host addons won't be correct, since as part of this optimization `ember-cli` returns an empty array for `addons`. The main reason for this is that `ember-engines` dedupe is _stateful_: it's possible for `_orginalAddons` to be clobbered by `addons` again so the real original addons will never be restored as part of `restoreOriginalAddons`, producing a build that's broken/incorrect.
For more information, see the PR adding this to `ember-cli`: https://github.com/ember-cli/ember-cli/pull/9487.
=> Support addon bundle caching as part of `ancestorHostAddons`

packages/ember-engines/addon/-private/engine-instance-ext.js, packages/ember-engines/tests/unit/engine-instance-test.js
It creates a deprecation warning to #756 starting the addition of _Engine Router Service._ 
Also, it provides suggestions for how to register the host's router as **hostRouter** and/or the root router as **appRouter**. 
Deprecations page has been linked - https://github.com/ember-engines/ember-engines.com/pull/111
=> Add deprecation warning to router service from host

packages/ember-engines/.template-lintrc.js, packages/ember-engines/tests/dummy/app/controllers/routable-engine-demo/index.js, packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/index.js, packages/ember-engines/tests/dummy/app/templates/application.hbs, packages/ember-engines/tests/dummy/app/templates/post.hbs, packages/ember-engines/tests/dummy/app/templates/routable-engine-demo.hbs, packages/ember-engines/tests/dummy/app/templates/routable-engine-demo/index.hbs
Closes #723.
We can update to ember-template-lint v3 later on.
=> Octanify dummy templates

packages/ember-engines/blueprints/in-repo-engine/index.js
it fixes the #726 
The code added is skipping the blueprint to add `mount('foo')` into `router.js` for routeless engines.
cc: @dgeb @rwjblue
=> Fix blueprint to routeless in-repo-engine

packages/ember-engines/package.json, yarn.lock
Fixes parallization issue with production builds.
=> Bump to `@embroider/macros@0.43.0` to fix parallelization with production builds

packages/ember-engines/addon/components/link-to-external.js
Prior to Ember 3.24, LinkToExternal only modifier the `routeKey` when inside an engine; that is, when `owner.mountPoint` exists. With the new class that exists for 3.24+, this behavior regressed. Now, `_namespaceRoute` is overridden in all cases, which means that if `LinkToExternal` ever gets rendered outside of an engine, it will automatically fail since `owner._getExternalRoute` will not find the specified route.
Why this matters: Routing code that may be invoked by an engine does not necessarily live in the same addon as the engine itself. If we extract code that is intended to link to external routes, we still need to be able to test it in those addons, which don't have engines of their own. It's also possible to write reusable code that is designed to be invoked both in an engine and …
=> [BUGFIX] Fallback to LinkTo behavior when outside an engine

packages/ember-engines/package.json, yarn.lock
This package uses `dependencySatisfies` of `@embroider/macros` which is
only reliable if a `peerDependency` for the package exists. If not, the
macro checks for a dependency in the `ember-engines` package when a
monorepo structure is used. This behaviour happens since embroider
v0.50.1 which includes an important fix for monorepos:
https://github.com/embroider-build/embroider/pull/1070
=> Fix usage of dependencySatisfies with a peerDependency

packages/ember-engines/lib/utils/deeply-non-duplicated-addon.js
The following is cobbled together from a JIRA ticket, so it is a bit fragmented.
When addons try to access `ember-cli-babel` during the build stage, `EMBER_ENGINES_ADDON_DEDUPE=true` can cause `this.addons` to be empty. Instead of requiring addons to do something like `this.addons.find(...) || this.project.addons.find(...)`, we should exclude `ember-cli-babel` from dedupe logic so it's available.
Related code in ember-engines:
https://github.com/ember-engines/ember-engines/blob/e24764341c0246a1dfa3875e7241482db1a61c26/packages/ember-engines/lib/engine-addon.js#L845
https://github.com/ember-engines/ember-engines/blob/e24764341c0246a1dfa3875e7241482db1a61c26/packages/ember-engines/lib/engine-addon.js#L397-L417
cc: @rwjblue @brendenpalmer
=> Add exclude list to addon dedupe logic

.github/workflows/ci.yml, packages/eager-blog/addon/templates/application.hbs, packages/ember-blog/addon/templates/components/hello-name.hbs, packages/ember-blog/addon/templates/index.hbs, packages/ember-blog/addon/templates/post.hbs, packages/ember-blog/addon/templates/post/comments.hbs, packages/ember-blog/addon/templates/post/error.hbs, packages/ember-chat/addon/templates/application.hbs, packages/ember-chat/addon/templates/components/hello-world.hbs, packages/ember-engines/addon/-private/engine-ext.js, packages/ember-engines/addon/components/link-to-component.js, packages/ember-engines/addon/components/link-to-external.js, packages/ember-engines/config/ember-try.js, packages/ember-engines/package.json, packages/ember-engines/tests/integration/component-with-link-to-external-test.js, packages/ember-engines/tests/unit/engine-instance-test.js, packages/ember-engines/tests/unit/initializers/engines-test.js
Built on top of https://github.com/ember-engines/ember-engines/pull/797
- Refactors link-to to LinkTo
- Requires @ember/legacy-built-in-components for ember > 3.24
- Refactors templates to use component/controller properties with `this`
=> Ember 4 compatibility

packages/ember-engines/addon-test-support/engine-resolver-for.js, packages/ember-engines/package.json, packages/ember-engines/tests/integration/engine-resolver-test.js
It adds a deprecation warning to `engineResolverFor` test helper given the new test API released at #653 
cc // @SergeAstapov @runspired
=> Add deprecation warning to `engineResolverFor`

.github/workflows/ci.yml, package.json, packages/ember-engines/README.md, packages/ember-engines/package.json
This is pre-requisite for bumping ember-asset-loader to 1.0.0, which will unblock https://github.com/ef4/ember-auto-import/pull/512
Node.js 12 was EOL in April 2022
=> Drop unsupported Node.js versions < 14

packages/ember-engines/node-tests/fixtures/expected-manifests.json
The change in https://github.com/ember-engines/ember-asset-loader/pull/123 means that the newer `ember-asset-loader` won't add to the manifest at all if there are no assets - previously there was the package name and an empty `assets` array.
This PR updates the fixtures to meet those new expectations.
=> update fixtures for ember-asset-loader@1.0.0 behavior

packages/ember-engines/package.json
as it's truly optional and package managers like pnpm don't blow up
=> Make @ember/legacy-built-in-components optional peer dependency

packages/ember-engines/lib/engine-addon.js, packages/ember-engines/node-tests/acceptance/build-test.js, packages/ember-engines/node-tests/fixtures/app-exports/data.js
setting an explicit treeForApp to an no-op function will ensure that no engine components leak into host app
some context for this PR:
the way to scaffold files in an engine is the same as an addon which is the conventional way to `ember generate component|helper|util ...`
this has the effect of adding files to the app re-export folder 
because this doesn't cause an obvious failure in the app everything still works it's likely to be missed by users and committed to the repository
the immediate non-obvious effect of this is that engine components will be directly usable in a host app no matter the type of engine
this can lead to the re-exports being included twice in the build
This change makes it so there is no way for those files to make it into the build and brings the functionality in …
=> enforce no app re-exports for engines

.github/workflows/plan-release.yml, .github/workflows/publish.yml, RELEASE.md, package.json, pnpm-lock.yaml
created using https://github.com/embroider-build/create-release-plan-setup
=> Setup release-plan

packages/ember-engines/addon-test-support/index.js, packages/ember-engines/tests/integration/setup-engine-test.js
If the engine is not registered to be destroyed, instances of the engine can be leaked as reported in https://github.com/ember-engines/ember-engines/issues/875.
=> Ensure that the engine is destroyed in tests when the test context is cleaned up.

packages/common-components/addon/components/spanish-greeting.js, packages/common-components/addon/templates/components/spanish-greeting.hbs, packages/eager-blog/addon/engine.js, packages/ember-blog/addon/components/hello-name.js, packages/ember-blog/addon/controllers/post.js, packages/ember-blog/addon/engine.js, packages/ember-blog/addon/routes/application.js, packages/ember-blog/addon/routes/index.js, packages/ember-blog/addon/routes/new.js, packages/ember-blog/addon/routes/post.js, packages/ember-blog/addon/routes/post/comments.js, packages/ember-blog/addon/routes/post/diggs.js, packages/ember-blog/addon/routes/post/likes.js, packages/ember-blog/addon/services/example-service.js, packages/ember-blog/addon/templates/post.hbs, packages/ember-chat/addon/components/hello-world.js, packages/ember-chat/addon/controllers/application.js, packages/ember-chat/addon/engine.js, packages/ember-chat/addon/services/example-service.js, packages/ember-chat/addon/templates/components/hello-world.hbs, packages/ember-engines/blueprints/in-repo-engine/routable-files/lib/__name__/addon/engine.js, packages/ember-engines/blueprints/in-repo-engine/routeless-files/lib/__name__/addon/engine.js, packages/ember-engines/tests/dummy/app/controllers/post.js, packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/after-model.js, packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/normal-route.js, packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/redirect.js, packages/ember-engines/tests/dummy/app/services/store.js, packages/ember-engines/tests/integration/component-with-link-to-external-test.js
Extract from #855 to keep it focused
=> Convert codebase to use native classes

.github/workflows/ci.yml, packages/ember-engines/config/ember-try.js
As we need to have a new major anyways, it's good time to chip away real old version of Ember.js which could make support for green CI harder.
Versions 3.25-3.28 came out with many niceties.
At the same time, users who still can't bump to v4 for whatever reason can use 3.28 easily.
=> Drop support for Ember.js < 3.28

packages/ember-engines/addon/-private/controller-ext.js, packages/ember-engines/addon/-private/deprecate-transition-methods.js, packages/ember-engines/addon/-private/route-ext.js, packages/ember-engines/tests/acceptance/routeable-engine-demo-test.js
Deprecate transition methods to match https://github.com/emberjs/rfcs/pull/674 before we remove them in #855
this will be last thing to release in v0.10.0 before we go v1.0.0
TODO:
=> [DEPRECATION] Deprecate transition methods of controller and route per RFC #674
